header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Bytedance Ltd.

  paths:
    - '**/*.go'
    - '**/*.s'

  paths-ignore:
    - 'internal/constraints/constraints.go'

  comment: on-failure