name: LicenseEye

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  license-header-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check License Header
        uses: apache/skywalking-eyes/header@v0.7.0